# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

saves you trouble of writing your own functions like mean
numpy comes with Anaconda 

!pip install package_name

In [2]:
import numpy as np

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

lefthand side is an assignment 
numpy array is what is returned - like a matrix
discrete uniform distribution - type of random numbers
random number generation

In [3]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
c2 = np.random.randint(1,10,2)
# to matrics demtiones 3 by 4 values inputed will be randomally selected 
# from values 1 to 9
d = np.arange(0,11,1)

In [4]:
print a

[ 0.  0.  0.]


In [5]:
print b

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [6]:
print c

[[[3 6 9 5]
  [7 9 9 5]
  [7 8 3 2]]

 [[5 3 3 9]
  [5 1 7 2]
  [1 8 1 3]]]


In [7]:
print c2

[4 9]


In [8]:
print d

[ 0  1  2  3  4  5  6  7  8  9 10]


What are these functions?

    arange?

In [9]:
# Note the way each array is printed:
print (a,b,c,d)

(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]]), array([[[3, 6, 9, 5],
        [7, 9, 9, 5],
        [7, 8, 3, 2]],

       [[5, 3, 3, 9],
        [5, 1, 7, 2],
        [1, 8, 1, 3]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))


In [10]:
## Arithmetic in arrays is element wise

In [11]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print a
print b

[20 30 40 50]
[0 1 2 3]


In [12]:
c = a-b
c

array([20, 29, 38, 47])

In [13]:
b**2

array([0, 1, 4, 9])

## Indexing, Slicing and Iterating

In [14]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2
# or
# map(lambda X: x**2, range(10))

In [15]:
print a

[ 0  1  4  9 16 25 36 49 64 81]


In [16]:
a[2:5]

array([ 4,  9, 16])

In [17]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [18]:
b = np.random.randint(1,100,(4,4))

In [19]:
print b
# descrite uniform

[[18 77  8 84]
 [28 12 22 36]
 [21 97  8 72]
 [91 18 77 83]]


In [20]:
# Guess the output
print(b[2,3])
# first by rows down 2 rows over 3
print(b[0,0])


72
18


In [21]:
b[0:3,1],b[:,1]

(array([77, 12, 97]), array([77, 12, 97, 18]))

In [22]:
b[1:3,:]

array([[28, 12, 22, 36],
       [21, 97,  8, 72]])

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [24]:
dates = pd.date_range('20140101',periods=6)
print dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')


In [25]:
dates = pd.date_range('20140101',periods=6)
print dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')


In [26]:
dates[0]
# inde of time stamp objects 
# collection of time stamps

Timestamp('2014-01-01 00:00:00', offset='D')

In [27]:
pd.Timestamp

pandas.tslib.Timestamp

In [28]:
date1 = dates[0]

In [29]:
print date1.day
print date1.month
print date1.year

1
1
2014


In [30]:
import time

# Time UUID appends random number to time stamp
# almost impossible to have duplicates

In [31]:
time.localtime()

time.struct_time(tm_year=2016, tm_mon=11, tm_mday=26, tm_hour=2, tm_min=51, tm_sec=2, tm_wday=5, tm_yday=331, tm_isdst=0)

In [32]:
np.random.randn(6,4)

array([[-0.37662389, -0.61123122, -0.41549413,  0.17990133],
       [ 0.29421842,  0.11314027,  0.41895195,  1.03917067],
       [-0.63476163, -1.10898225, -0.9649649 , -0.66349715],
       [-0.21044871, -0.86450867, -0.34719034, -0.53254072],
       [ 1.38738062, -0.16220368, -0.76452424, -0.71687276],
       [-0.82484832,  1.18534099,  0.63136579,  0.31254313]])

In [33]:
list("ABCD")

['A', 'B', 'C', 'D']

In [34]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [35]:
df.head(7)

A         B         C         D
2014-01-01 -0.214312 -0.261523 -0.973863  0.537310
2014-01-02 -0.659771  0.338855 -0.039328 -1.155038
2014-01-03  0.849951  0.282833  1.898673  1.112983
2014-01-04  0.534525 -0.030399 -0.504549  1.131880
2014-01-05 -1.481339  1.098920  0.503300 -0.199948
2014-01-06  0.499930  1.203067 -1.270046  0.890790

In [36]:
# Index, columns, underlying numpy data
df.T
# T - transpose

2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
A   -0.214312   -0.659771    0.849951    0.534525   -1.481339    0.499930
B   -0.261523    0.338855    0.282833   -0.030399    1.098920    1.203067
C   -0.973863   -0.039328    1.898673   -0.504549    0.503300   -1.270046
D    0.537310   -1.155038    1.112983    1.131880   -0.199948    0.890790

In [37]:
[3]*4

[3, 3, 3, 3]

In [38]:
np.array([3])*4


array([12])

In [39]:
np.array([3]*4)

array([3, 3, 3, 3])

In [40]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2
# hardcoding a new data frame with a dictionary ABCDE are KEYS. 
# assigning CONSTANTS - same value for an entire column
# pd.Series - a COLUMN
# C adds constraints on the length the amount of rows for the data frame - range(4) = 4 rows
# D 3 four times
# parse_dates string dates to dates
# parse_dates = [someColumn]

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [41]:
# With specific dtypes
df2.dtypes
# returns SCHEMA

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [42]:
df.head()

A         B         C         D
2014-01-01 -0.214312 -0.261523 -0.973863  0.537310
2014-01-02 -0.659771  0.338855 -0.039328 -1.155038
2014-01-03  0.849951  0.282833  1.898673  1.112983
2014-01-04  0.534525 -0.030399 -0.504549  1.131880
2014-01-05 -1.481339  1.098920  0.503300 -0.199948

In [43]:
df.tail()

A         B         C         D
2014-01-02 -0.659771  0.338855 -0.039328 -1.155038
2014-01-03  0.849951  0.282833  1.898673  1.112983
2014-01-04  0.534525 -0.030399 -0.504549  1.131880
2014-01-05 -1.481339  1.098920  0.503300 -0.199948
2014-01-06  0.499930  1.203067 -1.270046  0.890790

In [44]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [45]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.078503  0.438626 -0.064302  0.386329
std    0.882800  0.594101  1.153343  0.903403
min   -1.481339 -0.261523 -1.270046 -1.155038
25%   -0.548406  0.047909 -0.856534 -0.015633
50%    0.142809  0.310844 -0.271939  0.714050
75%    0.525876  0.908904  0.367643  1.057435
max    0.849951  1.203067  1.898673  1.131880

In [46]:
df.sort_values(by='B')
# inplace makes change on the original data frame
# df.sort_values(by = "B", inplace = True)
# transformation on the object

A         B         C         D
2014-01-01 -0.214312 -0.261523 -0.973863  0.537310
2014-01-04  0.534525 -0.030399 -0.504549  1.131880
2014-01-03  0.849951  0.282833  1.898673  1.112983
2014-01-02 -0.659771  0.338855 -0.039328 -1.155038
2014-01-05 -1.481339  1.098920  0.503300 -0.199948
2014-01-06  0.499930  1.203067 -1.270046  0.890790

### Selection

In [47]:
df[['A','B']]

A         B
2014-01-01 -0.214312 -0.261523
2014-01-02 -0.659771  0.338855
2014-01-03  0.849951  0.282833
2014-01-04  0.534525 -0.030399
2014-01-05 -1.481339  1.098920
2014-01-06  0.499930  1.203067

In [48]:
df[0:3]

A         B         C         D
2014-01-01 -0.214312 -0.261523 -0.973863  0.537310
2014-01-02 -0.659771  0.338855 -0.039328 -1.155038
2014-01-03  0.849951  0.282833  1.898673  1.112983

In [49]:
df[df.index == pd.Timestamp("2014-01-01")]

A         B         C        D
2014-01-01 -0.214312 -0.261523 -0.973863  0.53731

In [50]:
# By label
df.loc[dates[0]]
# grabs row by first date index 

A   -0.214312
B   -0.261523
C   -0.973863
D    0.537310
Name: 2014-01-01 00:00:00, dtype: float64

In [51]:
# multi-axis by label
df.loc[:,['A','B']]
# 

A         B
2014-01-01 -0.214312 -0.261523
2014-01-02 -0.659771  0.338855
2014-01-03  0.849951  0.282833
2014-01-04  0.534525 -0.030399
2014-01-05 -1.481339  1.098920
2014-01-06  0.499930  1.203067

In [52]:
df.loc["2014-01-01":"2014-01-03",["A","B"]]
# .loc - like a query 
# from one date to another date
# here the index column is not an integer- it is a date

A         B
2014-01-01 -0.214312 -0.261523
2014-01-02 -0.659771  0.338855
2014-01-03  0.849951  0.282833

In [53]:
# df[ (df.index >= "2014-01-01") & (df.index <= "2014-01-03")] ["A", "B"]

In [54]:
# Date Range

df.loc['20140102':'20140104',['B']]

B
2014-01-02  0.338855
2014-01-03  0.282833
2014-01-04 -0.030399

In [55]:
# Fast access to scalar
df.at[dates[1],'B']

0.33885492010973217

In [56]:
# iloc provides integer locations similar to np style
df.iloc[3:]
# row 3 onward
# better, safer
# better if you data is sorted

A         B         C         D
2014-01-04  0.534525 -0.030399 -0.504549  1.131880
2014-01-05 -1.481339  1.098920  0.503300 -0.199948
2014-01-06  0.499930  1.203067 -1.270046  0.890790

In [57]:
df[3:]

A         B         C         D
2014-01-04  0.534525 -0.030399 -0.504549  1.131880
2014-01-05 -1.481339  1.098920  0.503300 -0.199948
2014-01-06  0.499930  1.203067 -1.270046  0.890790

### Boolean Indexing

In [58]:
df[df.A < 0] # Basically a 'where' operation

A         B         C         D
2014-01-01 -0.214312 -0.261523 -0.973863  0.537310
2014-01-02 -0.659771  0.338855 -0.039328 -1.155038
2014-01-05 -1.481339  1.098920  0.503300 -0.199948

### Setting

In [59]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [60]:
df_posA

A         B         C         D
2014-01-01  0.214312  0.261523  0.973863 -0.537310
2014-01-02  0.659771 -0.338855  0.039328  1.155038
2014-01-03  0.849951  0.282833  1.898673  1.112983
2014-01-04  0.534525 -0.030399 -0.504549  1.131880
2014-01-05  1.481339 -1.098920 -0.503300  0.199948
2014-01-06  0.499930  1.203067 -1.270046  0.890790

In [61]:
df_posA

A         B         C         D
2014-01-01  0.214312  0.261523  0.973863 -0.537310
2014-01-02  0.659771 -0.338855  0.039328  1.155038
2014-01-03  0.849951  0.282833  1.898673  1.112983
2014-01-04  0.534525 -0.030399 -0.504549  1.131880
2014-01-05  1.481339 -1.098920 -0.503300  0.199948
2014-01-06  0.499930  1.203067 -1.270046  0.890790

In [62]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [63]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [64]:
df['F'] = s1

In [65]:
df

A         B         C         D    F
2014-01-01 -0.214312 -0.261523 -0.973863  0.537310  NaN
2014-01-02 -0.659771  0.338855 -0.039328 -1.155038  1.0
2014-01-03  0.849951  0.282833  1.898673  1.112983  2.0
2014-01-04  0.534525 -0.030399 -0.504549  1.131880  3.0
2014-01-05 -1.481339  1.098920  0.503300 -0.199948  4.0
2014-01-06  0.499930  1.203067 -1.270046  0.890790  5.0

### Missing Data

In [66]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [67]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [68]:
df1

A         B         C         D    F    E
2014-01-01 -0.214312 -0.261523 -0.973863  0.537310  NaN  1.0
2014-01-02 -0.659771  0.338855 -0.039328 -1.155038  1.0  1.0
2014-01-03  0.849951  0.282833  1.898673  1.112983  2.0  NaN
2014-01-04  0.534525 -0.030399 -0.504549  1.131880  3.0  NaN

In [69]:
# find where values are null
pd.isnull(df1)

A      B      C      D      F      E
2014-01-01  False  False  False  False   True  False
2014-01-02  False  False  False  False  False  False
2014-01-03  False  False  False  False  False   True
2014-01-04  False  False  False  False  False   True

### Operations

In [70]:
df.describe()

C:\Users\Amber\Anaconda2\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)


A         B         C         D         F
count  6.000000  6.000000  6.000000  6.000000  5.000000
mean  -0.078503  0.438626 -0.064302  0.386329  3.000000
std    0.882800  0.594101  1.153343  0.903403  1.581139
min   -1.481339 -0.261523 -1.270046 -1.155038  1.000000
25%   -0.548406  0.047909 -0.856534 -0.015633       NaN
50%    0.142809  0.310844 -0.271939  0.714050       NaN
75%    0.525876  0.908904  0.367643  1.057435       NaN
max    0.849951  1.203067  1.898673  1.131880  5.000000

In [71]:
df.mean(),df.mean(1) # Operation on two different axes

(A   -0.078503
 B    0.438626
 C   -0.064302
 D    0.386329
 F    3.000000
 dtype: float64, 2014-01-01   -0.228097
 2014-01-02   -0.103057
 2014-01-03    1.228888
 2014-01-04    0.826291
 2014-01-05    0.784187
 2014-01-06    1.264748
 Freq: D, dtype: float64)

### Applying functions

super important
make a new column - use apply

In [72]:
import pandas as pd
df2 = pd.DataFrame({"A": range(5), "B": range(5)})
df2.head()

A  B
0  0  0
1  1  1
2  2  2
3  3  3
4  4  4

In [73]:
df2["C"] = df2["A"]*2
# instead of using .apply
# or could do 
df2["C"] = df2.A.apply(lambda x: x*2)

In [74]:
df2.head()

A  B  C
0  0  0  0
1  1  1  2
2  2  2  4
3  3  3  6
4  4  4  8

In [75]:
df2.columns

Index([u'A', u'B', u'C'], dtype='object')

In [76]:
df2.drop("C", axis = 1)
# redefine it or add inplace = True - applies it to tht column
# or could slice it with df[["A", "B"]]

A  B
0  0  0
1  1  1
2  2  2
3  3  3
4  4  4

In [78]:
dfNames = pd.DataFrame(
    {"firstName": ["Amber", "Kumani"], "lastName": ["Keller", "Keller-S"]})

dfNames.head()

firstName  lastName
0     Amber    Keller
1    Kumani  Keller-S

In [79]:
def makeFull(obj):
    firstName = obj[0]
    lastName = obj[1]
    return firstName + " " + lastName
 
dfNames["fullname"] = dfNames.apply(makeFull, axis =1 )

In [80]:
dfNames.head()

firstName  lastName         fullname
0     Amber    Keller     Amber Keller
1    Kumani  Keller-S  Kumani Keller-S

In [81]:
dfNames["fullName"] = dfNames.firstName + " " + dfNames.lastName

In [82]:
dfNames.head()

firstName  lastName         fullname         fullName
0     Amber    Keller     Amber Keller     Amber Keller
1    Kumani  Keller-S  Kumani Keller-S  Kumani Keller-S

In [83]:
df

A         B         C         D    F
2014-01-01 -0.214312 -0.261523 -0.973863  0.537310  NaN
2014-01-02 -0.659771  0.338855 -0.039328 -1.155038  1.0
2014-01-03  0.849951  0.282833  1.898673  1.112983  2.0
2014-01-04  0.534525 -0.030399 -0.504549  1.131880  3.0
2014-01-05 -1.481339  1.098920  0.503300 -0.199948  4.0
2014-01-06  0.499930  1.203067 -1.270046  0.890790  5.0

In [84]:
df["E"] = df.D.apply(lambda x: x*2)
# don't run this cell - cell with apply over and overagain will keep applying a new column

In [85]:
df.head()

A         B         C         D    F         E
2014-01-01 -0.214312 -0.261523 -0.973863  0.537310  NaN  1.074620
2014-01-02 -0.659771  0.338855 -0.039328 -1.155038  1.0 -2.310077
2014-01-03  0.849951  0.282833  1.898673  1.112983  2.0  2.225966
2014-01-04  0.534525 -0.030399 -0.504549  1.131880  3.0  2.263759
2014-01-05 -1.481339  1.098920  0.503300 -0.199948  4.0 -0.399896

In [86]:
df2.apply(lambda x: x.max() - x.min())

A    4
B    4
C    8
dtype: int64

In [87]:
df.apply(np.cumsum)
# summarizing the columns - notice the new row at the bottom

A         B         C         D     F         E
2014-01-01 -0.214312 -0.261523 -0.973863  0.537310   NaN  1.074620
2014-01-02 -0.874082  0.077332 -1.013191 -0.617728   1.0 -1.235457
2014-01-03 -0.024132  0.360165  0.885482  0.495255   3.0  0.990510
2014-01-04  0.510394  0.329766  0.380932  1.627134   6.0  3.254269
2014-01-05 -0.970946  1.428686  0.884232  1.427187  10.0  2.854373
2014-01-06 -0.471016  2.631753 -0.385813  2.317977  15.0  4.635953

In [88]:
df.apply(np.cumsum, axis =1)

A         B         C         D         F         E
2014-01-01 -0.214312 -0.475835 -1.449698 -0.912388       NaN  0.162232
2014-01-02 -0.659771 -0.320916 -0.360244 -1.515283 -0.515283 -2.825360
2014-01-03  0.849951  1.132784  3.031457  4.144440  6.144440  8.370406
2014-01-04  0.534525  0.504127 -0.000423  1.131457  4.131457  6.395216
2014-01-05 -1.481339 -0.382419  0.120881 -0.079067  3.920933  3.521038
2014-01-06  0.499930  1.702997  0.432951  1.323741  6.323741  8.105321

In [89]:
df.apply(lambda x: x.max() - x.min())

A    2.331290
B    1.464590
C    3.168719
D    2.286918
F    4.000000
E    4.573836
dtype: float64

In [90]:
import math
df.apply(lambda x: math.exp(5)*x)

A           B           C           D           F  \
2014-01-01  -31.806689  -38.813508 -144.534047   79.743883         NaN   
2014-01-02  -97.918652   50.290529   -5.836864 -171.422909  148.413159   
2014-01-03  126.143885   41.976141  281.788039  165.181351  296.826318   
2014-01-04   79.330582   -4.511558  -74.881742  167.985835  445.239477   
2014-01-05 -219.850251  163.094262   74.696353  -29.674883  593.652636   
2014-01-06   74.196178  178.550952 -188.491534  132.204963  742.065796   

                     E  
2014-01-01  159.487767  
2014-01-02 -342.845819  
2014-01-03  330.362702  
2014-01-04  335.971670  
2014-01-05  -59.349767  
2014-01-06  264.409926

In [91]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Merge

In [92]:
np.random.randn(10,4)

array([[-0.15254401, -0.306248  , -1.1146901 ,  0.28549795],
       [ 0.2523809 ,  0.09367301, -1.01387651,  1.86417074],
       [ 1.10230723,  0.91379861, -0.59950813, -0.9718126 ],
       [-1.15101671, -1.3396349 , -0.48598874, -0.23058194],
       [ 1.36323363,  0.23679919, -0.01014426, -0.46967037],
       [-1.82746338, -0.67751269,  1.18570406, -1.02885156],
       [-0.38272666,  2.33651952,  0.49978538,  1.23811228],
       [-1.38588694, -2.48386989, -0.70391994,  1.53845454],
       [ 0.79924007, -0.10661725, -1.65054507, -1.61551495],
       [ 0.47454005,  0.55755201, -0.91183729, -1.08979829]])

In [93]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

0         1         2         3
0 -0.800030  1.129360 -0.984935  0.038379
1  0.488658 -0.864859  0.289721  0.436516
2  0.726966 -1.652176  0.606135 -0.492831
3 -0.216318  0.919230  0.452672 -0.339434
4  0.818438 -0.255273 -0.202203 -0.610496
5 -0.313833  0.814962  1.098669  0.536343
6  0.142882  0.115371  0.888095  1.165805
7 -0.659117  1.214804 -0.754226  1.006480
8 -1.267113  0.335354  0.593469 -0.224309
9 -0.376036 -1.106637  0.180086  0.199060

In [ ]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

In [ ]:
pd.concat(pieces)

In [ ]:
df3 = pd.concat(pieces)

In [ ]:
pieces = [df3, dfNames]
dfFinal = pd.concat(pieces)
dfFinal

In [ ]:
df3.append(dfNames)

In [ ]:
# Also can "Join" and "Append"
df

### Grouping


In [ ]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [ ]:
df

In [ ]:
df.groupby(['A','B']).sum()

In [ ]:
df.groupby(['A','B']).count().reset_index()

In [ ]:
# someAdding = {"A" : {"B" : "C"} }

df3 = df.groupby(['A','B']).apply(lambda x: len(x)).reset_index()
df3.columns = ["A", "B", "grouCount"]

In [ ]:
df3

In [ ]:
df3 = df.groupby(['A','B']).apply(lambda x: sum(x["C"])).reset_index()
df3.columns = ["A", "B", "sumC"]

same as SQL statement below
+ SELECT COUNT(*) AS groupCount <br/>
    + FROM df3
    + GROUPBY A,B
    

In [ ]:
df3

In [ ]:
df.groupby(['A','B']).size()

### Reshaping

In [ ]:
# You can also stack or unstack levels

In [1]:
a = df.groupby(['A','B']).sum()

NameError: name 'df' is not defined

In [ ]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

### Time Series


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [ ]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [ ]:
ts

In [ ]:
# Built in resampling
ts.resample('1Min').mean() # Resample secondly to 1Minutely

In [ ]:
# Many additional time series features
ts. #use tab

### Plotting


In [ ]:
ts.plot()

In [ ]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [ ]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [ ]:
# Pandas plot function will print with labels as default

In [ ]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas